#!/usr/bin/env bash

echo 'Starting . . .'

if [[ $(id -u) -ne 0 ]]
then
  cat <<__EOD__

  This script must be run as root.

  Run as:

    sudo bash -c $(curl -s https://raw.githubusercontent.com/galaxy3-net/sleuthkit-autopsy/main/Deploy)


__EOD__

  exit 1

fi

function strukturag ()
{
  echo "Installing ${1} . . ."
  git clone https://github.com/strukturag/${1}.git /usr/src/${1}/

  cd /usr/src/${1}/
  ./autogen.sh
  ./configure
  make
  make install
  echo "done . . ."
}

function libheif ()
{
  git clone https://github.com/strukturag/libheif.git /usr/src/libheif/

  cd /usr/src/libheif/
  ./autogen.sh
  ./configure
  make
  make install
  echo "done . . ."
}

function ImageMagick ()
{
  echo "Installing ImageMagick . . ."
  cd /usr/src/
  wget https://www.imagemagick.org/download/ImageMagick.tar.gz
  tar xf ImageMagick.tar.gz

  cd ImageMagick-7*
  ./configure --with-heic=yes
  make
  make install
  echo "done . . ."
}

function bellsoft-java8 ()
{
  echo "Installing bellsoft-java8 . . ."
  wget -q -O - https://download.bell-sw.com/pki/GPG-KEY-bellsoft | sudo apt-key add -
  egrep 'export JAVA_HOME=/usr/lib/jvm/bellsoft-java8-full-amd64' || \
      echo "deb [arch=amd64] https://apt.bell-sw.com/ stable main" | sudo tee /etc/apt/sources.list.d/bellsoft.list
  apt-get update
  apt-get install bellsoft-java8-full
  #    2. Set JAVA_HOME
  export JAVA_HOME=/usr/lib/jvm/bellsoft-java8-full-amd64
  echo "done . . ."
}

sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
apt-get update
#sudo apt-get upgrade -y 
apt-get --fix-broken install -y
apt-get install -y default-jdk testdisk build-essential autoconf libtool git-core
#apt-get install -y testdisk
apt autoremove -y
#apt-get install -y build-essential autoconf libtool git-core
apt-get build-dep -y imagemagick libmagickcore-dev libde265 libheif


stat /usr/src/libde265 || strukturag libde265
stat /usr/src/libheif || strukturag libheif
stat /usr/src/ImageMagick || ImageMagick

ldconfig

stat /usr/lib/jvm/bellsoft-java8-full-amd64 || bellsoft-java8


apt --fix-broken install -y
apt install -y libvmdk-dev libc3p0-java libsqlite3-dev libbfio1 libbfio-dev libafflib-dev libewf-dev libvmdk1 libvhdi1 libewf2 libafflib0v5

stat /root/ || unzip /Downloads/autopsy-4.17.0.zip -d /root/
dpkg -s sleuthkit-java || dpkg -i /Downloads/sleuthkit-java_4.10.1-1_amd64.deb
