#!/usr/bin/env bash

if [[ $(id -u) -ne 0 ]]
then
  cat <<__EOD__

  This script must be run as root.

  Run as:

    sudo bash -c $(curl -s https://raw.githubusercontent.com/galaxy3-net/sleuthkit-autopsy/main/Deploy)


__EOD__

  exit 1

fi

sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
apt-get update
#sudo apt-get upgrade -y 
apt-get --fix-broken install -y
apt-get install -y default-jdk
apt-get install -y testdisk
apt autoremove -t
apt-get update
apt-get install build-essential autoconf libtool git-core
apt-get build-dep imagemagick libmagickcore-dev libde265 libheif
cd /usr/src/

git clone https://github.com/strukturag/libde265.git
git clone https://github.com/strukturag/libheif.git

cd libde265/
./autogen.sh
./configure
make
make install

cd /usr/src/libheif/
./autogen.sh
./configure
make
make install

cd /usr/src/
wget https://www.imagemagick.org/download/ImageMagick.tar.gz
tar xf ImageMagick.tar.gz

cd ImageMagick-7*
./configure --with-heic=yes
make
make install

ldconfig

wget -q -O - https://download.bell-sw.com/pki/GPG-KEY-bellsoft | sudo apt-key add -
egrep 'export JAVA_HOME=/usr/lib/jvm/bellsoft-java8-full-amd64' || \
    echo "deb [arch=amd64] https://apt.bell-sw.com/ stable main" | sudo tee /etc/apt/sources.list.d/bellsoft.list
apt-get update
apt-get install bellsoft-java8-full
#    2. Set JAVA_HOME
export JAVA_HOME=/usr/lib/jvm/bellsoft-java8-full-amd64

apt --fix-broken install -y
apt install -y libvmdk-dev libc3p0-java libsqlite3-dev libbfio1 libbfio-dev libafflib-dev libewf-dev libvmdk1 libvhdi1 libewf2 libafflib0v5

cd /root
unzip /Downloads/autopsy-4.17.0.zip
dpkg -i /Downloads/sleuthkit-java_4.10.1-1_amd64.deb
